version: '2.2'
services:





  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.17.0
    environment:
      ELASTICSEARCH_HOSTS: localhost:9200

    networks:
      - es-network




networks:
  es-network:
    driver: bridge