version: '2.2'
services:





  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.11.1
    environment:
      ELASTICSEARCH_HOSTS: http://node01:9200
    volumes:
      - ./beat:/usr/share/metricbeat/metricbeat.yml:ro
    networks:
      - es-network




networks:
  es-network:
    driver: bridge