version: '2.2'
services:


  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    ports:
      - '5000:5000'
    volumes:
      - type: bind
        source: .
        target: /usr/share/logstash/pipeline
        read_only: true



  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.17.0
    environment:
      ELASTICSEARCH_HOSTS: localhost:9200

    networks:
      - es-network




networks:
  es-network:
    driver: bridge