version: '3'
services:
  cerebro:
    image: lmenezes/cerebro
    environment: 
      - AUTH_TYPE=ldap
      - LDAP_URL=ldap://ldap:389
      - LDAP_BASE_DN=DC=example,DC=org
      - LDAP_METHOD=simple
      - LDAP_USER_TEMPLATE=uid=%s,%s
      # Uncomment these env vars if cerebro <= 0.9.2. In these versions it's needed to configure an user that can perform searches
      # - LDAP_BIND_DN=cn=admin,dc=example,dc=org
      # - LDAP_BIND_PWD=admin
    ports: 
      - 9000:9000
  open_ldap:
    image: osixia/openldap:1.4.0
    container_name: ldap
    ports: 
      - 389:389
      - 636:636
    volumes: 
      - ./users:/opt
