version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  logstash:  
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,z
      # - ./logstash/jdbc/mysql-connector-java-8.0.22.jar:/usr/share/logstash/mysql-connector-java-8.0.22.jar:ro,z
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  cerebro: 
    image: lmenezes/cerebro   
    ports:
      - "9000:9000"
    networks:
      - elk     
  cadvisor: 
    image: google/cadvisor
    ports:
      - "8080:8080"
    networks:
      - elk         

  mysql:
    image: mariadb
    container_name: maria_elastic
    ports:
        - "3306:3306" 
    environment:
        MYSQL_ROOT_PASSWORD: root   
        MYSQL_USER: chan
        MYSQL_PASSWORD: 961421180   
        MYSQL_DATABASE: appsalon
    volumes:
      - C:\DEVLAB\BBDD\mariadb:/var/lib/mysql              
    networks:
      - elk    

  sqlserver:
  # https://hub.docker.com/_/microsoft-mssql-server
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    user: '0:0'
    container_name: sqlserver2019
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 44795240Aa
      MSSQL_PID: Express
    volumes:
      - C:\DEVLAB\BBDD\mssql:/var/opt/mssql/data 
    networks:
      - elk      
networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:

